name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set lowercase variables
        id: vars
        run: |
          # set lowercase owner and repo (in case of uppercase in GitHub context)
          echo "repo_lowercase=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "owner_lowercase=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.repo_lowercase }}:latest
            ghcr.io/${{ steps.vars.outputs.repo_lowercase }}:${{ github.sha }}

      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
          IMAGE_REPO: ghcr.io/${{ steps.vars.outputs.repo_lowercase }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials

          rm -rf gitops

          git clone https://github.com/yancers/kubernetes-gitops.git gitops
          cd gitops

          # Update the image in deployment.yaml to the new tag
          if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|image: .*\(ghcr.io/[a-z0-9\-\/]\+\):.*|image: ${IMAGE_REPO}:${IMAGE_TAG}|g" deployment.yaml
          else
            sed -i "s|image: .*\(ghcr.io/[a-z0-9\-\/]\+\):.*|image: ${IMAGE_REPO}:${IMAGE_TAG}|g" deployment.yaml
          fi

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image to ${IMAGE_TAG}" || echo "No changes to commit"
          git push -f https://${GIT_TOKEN}@github.com/yancers/kubernetes-gitops.git main
